spring:
  application:
    name: collector

  datasource:
    url: ${BOT_DB_URL}
    username: ${BOT_DB_USERNAME}
    password: ${BOT_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

  liquibase:
    change-log: classpath:db/changelog/master.xml
    enabled: true

casdoor:
  endpoint: ${CASDOOR_ENDPOINT}
  client-id: ${CASDOOR_CLIENT_ID}
  client-secret: ${CASDOOR_CLIENT_SECRET}
  certificate: ${CASDOOR_CERTIFICATE}
  organization-name: ${CASDOOR_ORGANIZATION_NAME}
  application-name: ${CASDOOR_APPLICATION_NAME}

app:
  telegram:
    url: https://api.telegram.org/bot
    token: ${APP_TELEGRAM_TOKEN}
    update-listener-sleep: 1s
    debug: false

  chat-authentication:
    callback: ${APP_CHAT_AUTHENTICATION_CALLBACK}
